return {
    "nvim-treesitter/nvim-treesitter",
    highlight = { enable = true },
    indent = { enable = true },
    opts = {
        ensure_installed = {
            "bash",
            "c",
            "diff",
            "html",
            "css",
            "javascript",
            "jsdoc",
            "json",
            "jsonc",
            "lua",
            "luadoc",
            "luap",
            "markdown",
            "markdown_inline",
            "printf",
            "python",
            "query",
            "regex",
            "toml",
            "tsx",
            "typescript",
            "vim",
            "vimdoc",
            "xml",
            "yaml",
            "go",
            "dockerfile",
            "svelte",
            "solidity",
            "cmake",
            "rust",
            "sql",
        },
    },
}
